# Project: VLSM1
# Makefile created by Dev-C++ 5.3.0.4

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"D:/Angel/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"D:/Angel/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"D:/Angel/Dev-Cpp/MinGW32/include"
BIN      = VLSM1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
